# Netlify configuration for React SPA

[build]
  # Build command for your app
  command = "npm run build"
  # Directory that contains the deploy-ready HTML files and assets
  publish = "dist"

# Redirect all non-file requests to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 